
#!/bin/bash
echo install tornado....
pip install tornado
echo starting Node....
npm init -y	
echo Install electron....
npm install --save-dev electron
echo starting server....
python server.py & npx electron .
